version: "3.8"

networks:
  servers:

services:

  balancer:
    build: .
    command: "lb"
    networks:
      - servers
    ports:
      - "8090:8090"

  server1:
    build: .
    networks:
      - servers
    depends_on:
      - db
    ports:
      - "8080:8080"

  server2:
    build: .
    networks:
      - servers
    depends_on:
      - db
    ports:
      - "8081:8080"

  server3:
    build: .
    networks:
      - servers
    depends_on:
      - db
    ports:
      - "8082:8080"

  db:
    build: .
    command: "db"
    networks:
      - servers
    ports:
      - "8083:8081"
    volumes:
      - dbdata:/app/data

volumes:
  dbdata:
